//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSMU.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMSdb : DbContext
    {
        public CMSdb()
            : base("name=CMSdb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Registrar> Registrars { get; set; }
        public virtual DbSet<requester> requesters { get; set; }
        public virtual DbSet<Reuest> Reuests { get; set; }
        public virtual DbSet<Student> Students { get; set; }
    }
}
