//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSMU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reuest
    {
        public int ReqId { get; set; }
        public string StuNo { get; set; }
        public Nullable<short> Satus { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> PayType { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public Nullable<short> Payed { get; set; }
        public Nullable<short> Ready { get; set; }
    }
}
