//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faculty_Batch
    {
        public int Id { get; set; }
        public Nullable<int> BatchId { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Faculty Faculty { get; set; }
    }
}
