//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.Payments = new HashSet<Payment>();
            this.Request_Certificate = new HashSet<Request_Certificate>();
        }
    
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> DeliveryId { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<bool> IsChecked { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsDeliverd { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual DeliveryType DeliveryType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request_Certificate> Request_Certificate { get; set; }
        public virtual Student Student { get; set; }
    }
}
