//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTemporaryUrl
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> ShortCode { get; set; }
        public Nullable<System.DateTime> Generated { get; set; }
        public Nullable<System.DateTime> Expires { get; set; }
        public Nullable<bool> IsUsed { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
